### ISSUE TITLE
Incompatibility with brms 2.12.0

### ISSUE THREAD

**Issue by IvanUkhov** [rpsychologist/marginal-two-part#1]
Hi, the tutorial works great with brms 2.10.0 (September 2019); however, with 2.12.0, the [first invocation of `plot_trend`](https://github.com/rpsychologist/marginal-two-part/blob/master/tutorial.Rmd#L141) gives the following error:

```
Error in get(pp_expect_fun, draws$family$env) : object 'pp_expect_hurdle_gamma_mtp' not found
```

The [second one](https://github.com/rpsychologist/marginal-two-part/blob/master/tutorial.Rmd#L150) works fine. And then the posterior predictive check fails with the following:

```
Error in get(pp_fun, draws$family$env) : object 'posterior_predict_hurdle_gamma_mtp' not found`
```

Is it a quick fix that is required, or is it something more profound?

**Comment by rpsychologist** [comment]
Thanks! It should be a quick fix, the `fitted `and `predict` methods have been renamed in `brms`. I'll update the code tomorrow.

**Comment by rpsychologist** [comment]
Everything should work with brms 2.12.0 now

**Comment by IvanUkhov** [comment]
It does. Thank you for the quick response and solution!
